#ifdef __OBJC__
#import <UIKit/UIKit.h>
#else
#ifndef FOUNDATION_EXPORT
#if defined(__cplusplus)
#define FOUNDATION_EXPORT extern "C"
#else
#define FOUNDATION_EXPORT extern
#endif
#endif
#endif

#import <FaceDecorationKitSceneEffects/FDKBadTVFilter.h>
#import <FaceDecorationKitSceneEffects/FDKBarrelBlurFilter.h>
#import <FaceDecorationKitSceneEffects/FDKBGhostFilterGroup.h>
#import <FaceDecorationKitSceneEffects/FDKBlack3Filter.h>
#import <FaceDecorationKitSceneEffects/FDKBlack3FilterGroup.h>
#import <FaceDecorationKitSceneEffects/FDKBlackWhiteFilter.h>
#import <FaceDecorationKitSceneEffects/FDKBlurMirrorFilter.h>
#import <FaceDecorationKitSceneEffects/FDKBlurMirrorFilterGroup.h>
#import <FaceDecorationKitSceneEffects/FDKBlursplicFilterGroup.h>
#import <FaceDecorationKitSceneEffects/FDKBlushingFilter.h>
#import <FaceDecorationKitSceneEffects/FDKBrightnessFilter.h>
#import <FaceDecorationKitSceneEffects/FDKBwlineFilterGroup.h>
#import <FaceDecorationKitSceneEffects/FDKBwprismFilterGroup.h>
#import <FaceDecorationKitSceneEffects/FDKBWReliefFilter.h>
#import <FaceDecorationKitSceneEffects/FDKBWReliefFilterGroup.h>
#import <FaceDecorationKitSceneEffects/FDKColineFilter.h>
#import <FaceDecorationKitSceneEffects/FDKDarkPassFilterGroup.h>
#import <FaceDecorationKitSceneEffects/FDKDawnbringerFilter.h>
#import <FaceDecorationKitSceneEffects/FDKDazzlingFilter.h>
#import <FaceDecorationKitSceneEffects/FDKDazzlingFilterGroup.h>
#import <FaceDecorationKitSceneEffects/FDKDistortedTVFilter.h>
#import <FaceDecorationKitSceneEffects/FDKDizzyFilter.h>
#import <FaceDecorationKitSceneEffects/FDKDotScreenFilter.h>
#import <FaceDecorationKitSceneEffects/FDKDoubleBWFilter.h>
#import <FaceDecorationKitSceneEffects/FDKDrosteFilter.h>
#import <FaceDecorationKitSceneEffects/FDKDuoColor4Filter.h>
#import <FaceDecorationKitSceneEffects/FDKDuoColor9Filter.h>
#import <FaceDecorationKitSceneEffects/FDKDuoToneFilter.h>
#import <FaceDecorationKitSceneEffects/FDKEdgesFilter.h>
#import <FaceDecorationKitSceneEffects/FDKFilm3Filter.h>
#import <FaceDecorationKitSceneEffects/FDKFilm3FilterGroup.h>
#import <FaceDecorationKitSceneEffects/FDKFilmFilter.h>
#import <FaceDecorationKitSceneEffects/FDKFlashBackFilter.h>
#import <FaceDecorationKitSceneEffects/FDKGameFilter.h>
#import <FaceDecorationKitSceneEffects/FDKGlitchBurrFilter.h>
#import <FaceDecorationKitSceneEffects/FDKGlitchFilter.h>
#import <FaceDecorationKitSceneEffects/FDKGlitchyDistortionFilter.h>
#import <FaceDecorationKitSceneEffects/FDKGlitchyDistortionFilterGroup.h>
#import <FaceDecorationKitSceneEffects/FDKGlowFilter.h>
#import <FaceDecorationKitSceneEffects/FDKGrainCamFilter.h>
#import <FaceDecorationKitSceneEffects/FDKGridFrame2Filter.h>
#import <FaceDecorationKitSceneEffects/FDKGridFrame2FilterGroup.h>
#import <FaceDecorationKitSceneEffects/FDKGridFrameFilter.h>
#import <FaceDecorationKitSceneEffects/FDKGridFrameFilterGroup.h>
#import <FaceDecorationKitSceneEffects/FDKHandheldFilter.h>
#import <FaceDecorationKitSceneEffects/FDKHeartbeatFilter.h>
#import <FaceDecorationKitSceneEffects/FDKHueFilter.h>
#import <FaceDecorationKitSceneEffects/FDKHuesatFilter.h>
#import <FaceDecorationKitSceneEffects/FDKHueSaturation9Filter.h>
#import <FaceDecorationKitSceneEffects/FDKHueTVFilterGroup.h>
#import <FaceDecorationKitSceneEffects/FDKHyperZoom4Filter.h>
#import <FaceDecorationKitSceneEffects/FDKHyperZoom4FilterGroup.h>
#import <FaceDecorationKitSceneEffects/FDKHyperZoom9Filter.h>
#import <FaceDecorationKitSceneEffects/FDKJitterFilter.h>
#import <FaceDecorationKitSceneEffects/FDKLightningFilter.h>
#import <FaceDecorationKitSceneEffects/FDKLineGlitchFilter.h>
#import <FaceDecorationKitSceneEffects/FDKLinocutFilter.h>
#import <FaceDecorationKitSceneEffects/FDKLowPassFilterGroup.h>
#import <FaceDecorationKitSceneEffects/FDKMirror2Filter.h>
#import <FaceDecorationKitSceneEffects/FDKMirror4Filter.h>
#import <FaceDecorationKitSceneEffects/FDKMirror9Filter.h>
#import <FaceDecorationKitSceneEffects/FDKMoneyFilter.h>
#import <FaceDecorationKitSceneEffects/FDKMonitorFilter.h>
#import <FaceDecorationKitSceneEffects/FDKNoiseLineFilter.h>
#import <FaceDecorationKitSceneEffects/FDKNostalgiaFilter.h>
#import <FaceDecorationKitSceneEffects/FDKNotecolorFilter.h>
#import <FaceDecorationKitSceneEffects/FDKOldFilmFilter.h>
#import <FaceDecorationKitSceneEffects/FDKOldFilmFilterGroup.h>
#import <FaceDecorationKitSceneEffects/FDKParticleBlurFilter.h>
#import <FaceDecorationKitSceneEffects/FDKPartitionFilterGroup.h>
#import <FaceDecorationKitSceneEffects/FDKPixelate4Filter.h>
#import <FaceDecorationKitSceneEffects/FDKPixelGFilter.h>
#import <FaceDecorationKitSceneEffects/FDKPixelShiftFilter.h>
#import <FaceDecorationKitSceneEffects/FDKPoshueFilterGroup.h>
#import <FaceDecorationKitSceneEffects/FDKPosterizeBasicFilter.h>
#import <FaceDecorationKitSceneEffects/FDKPosterizeFilter.h>
#import <FaceDecorationKitSceneEffects/FDKPsychedelicLondon2Filter.h>
#import <FaceDecorationKitSceneEffects/FDKPsychedelicLondon2FilterGroup.h>
#import <FaceDecorationKitSceneEffects/FDKRainbow4Filter.h>
#import <FaceDecorationKitSceneEffects/FDKRainbow4FilterGroup.h>
#import <FaceDecorationKitSceneEffects/FDKRainbowFilter.h>
#import <FaceDecorationKitSceneEffects/FDKRainDropsFilter.h>
#import <FaceDecorationKitSceneEffects/FDKRaindropsOnWindowFilter.h>
#import <FaceDecorationKitSceneEffects/FDKRGBFilter.h>
#import <FaceDecorationKitSceneEffects/FDKRGBGhostFilter.h>
#import <FaceDecorationKitSceneEffects/FDKRGBHueFilterGroup.h>
#import <FaceDecorationKitSceneEffects/FDKRGBShift2Filter.h>
#import <FaceDecorationKitSceneEffects/FDKRippleFilter.h>
#import <FaceDecorationKitSceneEffects/FDKRota4Filter.h>
#import <FaceDecorationKitSceneEffects/FDKRota4FilterGroup.h>
#import <FaceDecorationKitSceneEffects/FDKScaleFilter.h>
#import <FaceDecorationKitSceneEffects/FDKScanlinesFilter.h>
#import <FaceDecorationKitSceneEffects/FDKScanvibrateFilter.h>
#import <FaceDecorationKitSceneEffects/FDKSecretFilterGroup.h>
#import <FaceDecorationKitSceneEffects/FDKShadowingFilter.h>
#import <FaceDecorationKitSceneEffects/FDKSlicesFilter.h>
#import <FaceDecorationKitSceneEffects/FDKSolapixFilterGroup.h>
#import <FaceDecorationKitSceneEffects/FDKSolarizeFilter.h>
#import <FaceDecorationKitSceneEffects/FDKSoulstuffFilter.h>
#import <FaceDecorationKitSceneEffects/FDKSpookyFilter.h>
#import <FaceDecorationKitSceneEffects/FDKTiltFilter.h>
#import <FaceDecorationKitSceneEffects/FDKTransformDuoTonFilter.h>
#import <FaceDecorationKitSceneEffects/FDKTranslationFilter.h>
#import <FaceDecorationKitSceneEffects/FDKTranslationFilterGroup.h>
#import <FaceDecorationKitSceneEffects/FDKTripleBlurFilter.h>
#import <FaceDecorationKitSceneEffects/FDKTripleFlashFilter.h>
#import <FaceDecorationKitSceneEffects/FDKTrippyFilter.h>
#import <FaceDecorationKitSceneEffects/FDKTrippyFilterGroup.h>
#import <FaceDecorationKitSceneEffects/FDKTVGlitchFilter.h>
#import <FaceDecorationKitSceneEffects/FDKTwistAroundFilter.h>
#import <FaceDecorationKitSceneEffects/FDKVCRDistortionFilter.h>
#import <FaceDecorationKitSceneEffects/FDKVCRDistortionFilterGroup.h>
#import <FaceDecorationKitSceneEffects/FDKVenueFilter.h>
#import <FaceDecorationKitSceneEffects/FDKVenueFilterGroup.h>
#import <FaceDecorationKitSceneEffects/FDKVHSFilter.h>
#import <FaceDecorationKitSceneEffects/FDKVHSStreakFilter.h>
#import <FaceDecorationKitSceneEffects/FDKVHSStreakFilterGroup.h>
#import <FaceDecorationKitSceneEffects/FDKVignette3Filter.h>
#import <FaceDecorationKitSceneEffects/FDKVignette3FilterGroup.h>
#import <FaceDecorationKitSceneEffects/FDKVignetteFilter.h>
#import <FaceDecorationKitSceneEffects/FDKVintageTVFilterGroup.h>
#import <FaceDecorationKitSceneEffects/FDKWavyTwistFilter.h>
#import <FaceDecorationKitSceneEffects/FDKWeirdFilter.h>
#import <FaceDecorationKitSceneEffects/FDKWobbleFilter.h>
#import <FaceDecorationKitSceneEffects/FDKXRayFilter.h>
#import <FaceDecorationKitSceneEffects/FDKZoomFilter.h>
#import <FaceDecorationKitSceneEffects/FDKSceneEffectsUnity.h>
#import <FaceDecorationKitSceneEffects/FDKSELookupFilter.h>
#import <FaceDecorationKitSceneEffects/FDKShaderToyFilter.h>
#import <FaceDecorationKitSceneEffects/FDKShaderToyTwoInputFilter.h>

#if __has_include(<FaceDecorationKitSceneEffects/FDKBWReliefFilterGroup+LocalImage.h>)
#import <FaceDecorationKitSceneEffects/FDKBWReliefFilterGroup+LocalImage.h>
#import <FaceDecorationKitSceneEffects/FDKFilm3FilterGroup+LocalImage.h>
#import <FaceDecorationKitSceneEffects/FDKGlitchyDistortionFilterGroup+LocalImage.h>
#import <FaceDecorationKitSceneEffects/FDKHyperZoom4FilterGroup+LocalImage.h>
#import <FaceDecorationKitSceneEffects/FDKOldFilmFilterGroup+LocalImage.h>
#import <FaceDecorationKitSceneEffects/FDKPsychedelicLondon2FilterGroup+LocalImage.h>
#import <FaceDecorationKitSceneEffects/FDKRainbow4FilterGroup+LocalImage.h>
#import <FaceDecorationKitSceneEffects/FDKRota4FilterGroup+LocalImage.h>
#import <FaceDecorationKitSceneEffects/FDKSecretFilterGroup+LocalImage.h>
#import <FaceDecorationKitSceneEffects/FDKTranslationFilterGroup+LocalImage.h>
#import <FaceDecorationKitSceneEffects/FDKVCRDistortionFilterGroup+LocalImage.h>
#import <FaceDecorationKitSceneEffects/FDKVHSStreakFilterGroup+LocalImage.h>
#import <FaceDecorationKitSceneEffects/FDKVignette3FilterGroup+LocalImage.h>
#endif

FOUNDATION_EXPORT double FaceDecorationKitSceneEffectsVersionNumber;
FOUNDATION_EXPORT const unsigned char FaceDecorationKitSceneEffectsVersionString[];

